# <center>Dispersive Flies Optimization</center>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import Libraries

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Load Dataset

In [7]:
data = pd.read_csv('/content/drive/MyDrive/Swarm_Behaviour.csv')

In [8]:
data.head()

,x1,y1,xVel1,yVel1,xA1,yA1,xS1,yS1,xC1,yC1,...,yVel200,xA200,yA200,xS200,yS200,xC200,yC200,nAC200,nS200,Swarm_Behaviour
0,562.05,-0.62,-10.70,-4.33,0.00,0.00,0.0,0.0,0.00,0.00,...,-15.15,0.00,0.00,0.00,0.00,0.00,0.0,28,0,0.0
1,175.66,-57.09,2.31,-2.67,0.00,0.00,0.0,0.0,0.00,0.00,...,-3.48,0.00,0.00,0.00,0.00,0.00,0.0,4,0,0.0
2,200.16,-320.07,4.01,-6.37,0.00,0.00,0.0,0.0,0.18,-0.26,...,-9.38,0.00,0.00,0.00,0.00,-0.11,-0.3,15,1,0.0
3,316.99,-906.84,0.85,9.17,-0.17,1.03,0.0,0.0,0.00,0.00,...,10.39,-0.26,1.01,0.00,0.00,0.00,0.0,16,0,0.0
4,1277.68,908.54,-2.02,8.23,-1.00,1.00,0.0,0.0,0.00,0.00,...,13.91,-1.00,0.00,3.21,15.67,0.00,0.0,12,0,0.0

## Data Processing

#### Label Encoding

In [9]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

data = data.apply(le.fit_transform)

In [10]:
data.head()

,x1,y1,xVel1,yVel1,xA1,yA1,xS1,yS1,xC1,yC1,...,yVel200,xA200,yA200,xS200,yS200,xC200,yC200,nAC200,nS200,Swarm_Behaviour
0,10795,9519,240,735,100,98,372,351,253,245,...,83,100,100,356,332,212,226,28,0,0
1,8651,9096,1432,899,100,98,372,351,253,245,...,855,100,100,356,332,212,226,4,0,0
2,8774,6531,1596,558,100,98,372,351,271,219,...,346,100,100,356,332,201,196,15,1,0
3,9514,698,1286,2016,83,196,372,351,253,245,...,2108,74,194,356,332,212,226,16,0,0
4,15926,16031,1000,1922,0,193,372,351,253,245,...,2286,1,100,588,648,212,226,12,0,0

#### Feature Scaling

In [11]:
from sklearn import preprocessing
X = data.values
min_max_scaler = preprocessing.MinMaxScaler()
data_scaled = min_max_scaler.fit_transform(X)
df = pd.DataFrame(data_scaled)

In [12]:
df.columns = data.columns

In [13]:
df.head()

,x1,y1,xVel1,yVel1,xA1,yA1,xS1,yS1,xC1,yC1,...,yVel200,xA200,yA200,xS200,yS200,xC200,yC200,nAC200,nS200,Swarm_Behaviour
0,0.634664,0.567249,0.105125,0.299389,0.546448,0.497462,0.529915,0.500713,0.513185,0.494949,...,0.034411,0.515464,0.507614,0.509299,0.501511,0.467991,0.475789,0.205882,0.000000,0.0
1,0.508613,0.542042,0.627245,0.366191,0.546448,0.497462,0.529915,0.500713,0.513185,0.494949,...,0.354478,0.515464,0.507614,0.509299,0.501511,0.467991,0.475789,0.029412,0.000000,0.0
2,0.515845,0.389190,0.699080,0.227291,0.546448,0.497462,0.529915,0.500713,0.549696,0.442424,...,0.143449,0.515464,0.507614,0.509299,0.501511,0.443709,0.412632,0.110294,0.015625,0.0
3,0.559351,0.041595,0.563294,0.821181,0.453552,0.994924,0.529915,0.500713,0.513185,0.494949,...,0.873964,0.381443,0.984772,0.509299,0.501511,0.467991,0.475789,0.117647,0.000000,0.0
4,0.936328,0.955307,0.438020,0.782892,0.000000,0.979695,0.529915,0.500713,0.513185,0.494949,...,0.947761,0.005155,0.507614,0.841202,0.978852,0.467991,0.475789,0.088235,0.000000,0.0

#### Define Target and Feature Variables

In [14]:
#feature variables
X = df.drop(['Swarm_Behaviour'], axis=1).values

#target variable
y = df['Swarm_Behaviour'].values

#### Train-Test Split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=23)

## Data Analysis

In [16]:
df.shape

(23309, 2401)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23309 entries, 0 to 23308
Columns: 2401 entries, x1 to Swarm_Behaviour
dtypes: float64(2401)
memory usage: 427.0 MB

In [18]:
df["Swarm_Behaviour"].value_counts()

Swarm_Behaviour
0.0    15355
1.0     7954
Name: count, dtype: int64

## Classification

### In this work, at first classification models has been applied without optimization
#### Classifier Used-
- Logistic Regression
- Support Vector Machine
- Decision Tree
- Random Forrest
- Neural Networks

In [20]:
models = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models['Logistic Regression'] = LogisticRegression(solver='lbfgs', max_iter=2000)

# Support Vector Machines
from sklearn.svm import SVC
models['Support Vector Machines'] = SVC(kernel='linear')

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models['Decision Trees'] = DecisionTreeClassifier()

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models['Random Forest'] = RandomForestClassifier()

# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models['K-Nearest Neighbor'] = KNeighborsClassifier()

# Neural Networks
from sklearn.neural_network import MLPClassifier
models['Neural Networks'] = MLPClassifier()

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix

accuracy = {}

for key in models.keys():

    # Fit the classifier
    models[key].fit(X_train, y_train)

    # Make predictions
    predictions = models[key].predict(X_test)

    # Calculate metrics
    accuracy[key] = accuracy_score(predictions, y_test)

In [22]:
df_model = pd.DataFrame(index=models.keys(), columns=['Accuracy'])
df_model['Accuracy'] = accuracy.values()

df_model

                         Accuracy
Logistic Regression      0.881596
Support Vector Machines  0.877020
Decision Trees           0.872301
Random Forest            0.871586
K-Nearest Neighbor       0.888460
Neural Networks          0.896897

## Implementation of DFO Algorithm

#### FITNESS FUNCTION (SPHERE FUNCTION)

In [23]:
def f(x): # x IS A VECTOR REPRESENTING ONE FLY
    sum = 0.0
    for i in range(len(x)):
        sum = sum + np.power(x[i],2)
    return sum

#### Set population size N, dimensionality D, disturbance threshold delta and iterations

In [24]:
X_train.shape[0]

16316

In [25]:
X_train.shape[1]

2400

In [26]:
N = 50 # POPULATION SIZE
D = X_train.shape[1] # DIMENSIONALITY
delta = 0.005 # DISTURBANCE THRESHOLD
maxIterations = 50 # ITERATIONS ALLOWED

#### PHASE INITIALIZATION

In [29]:
lb  = 0
ub  = 1
A = np.random.uniform(lb, ub, (N, D))  # random initialization
fitness = [None]*N  # EMPTY FITNESS ARRAY OF SIZE N

#### MAIN DFO LOOP

In [30]:
for itr in range (maxIterations):
    for i in range(N): # EVALUATION
        fitness[i] = f(A[i,])
    s = np.argmin(fitness) # FIND BEST FLY

    if (itr%1 == 0): # PRINT BEST FOR EACH ITERATIONS
        print ("Iteration:", itr, "\tBest fly index:", s,
               "\tFitness value:", fitness[s])

    # TAKE EACH FLY INDIVIDUALLY
    for i in range(N):
        if i == s: continue # ELITIST STRATEGY

        # FIND BEST NEIGHBOUR
        left = (i-1)%N
        right = (i+1)%N
        bNeighbour = right if fitness[right]<fitness[left] else left

        for d in range(D): # UPDATE EACH DIMENSION SEPARATELY
            if (np.random.rand() < delta):
                A[i,d] = X_train[i,d]
                continue;

            u = np.random.rand()
            A[i,d] = A[bNeighbour,d] + u*(A[s,d] - A[i,d])

for i in range(N): fitness[i] = f(A[i,]) # EVALUATION
s = np.argmin(fitness) # FIND BEST FLY

print("\nFinal best fitness:\t", fitness[s])
print("\nBest fly position:\n",  A[s,])

Iteration: 0 	Best fly index: 20 	Fitness value: 776.0896314533197
Iteration: 1 	Best fly index: 20 	Fitness value: 776.0896314533197
Iteration: 2 	Best fly index: 21 	Fitness value: 723.7536299410114
Iteration: 3 	Best fly index: 21 	Fitness value: 723.7536299410114
Iteration: 4 	Best fly index: 21 	Fitness value: 723.7536299410114
Iteration: 5 	Best fly index: 22 	Fitness value: 718.7992110906671
Iteration: 6 	Best fly index: 22 	Fitness value: 718.7992110906671
Iteration: 7 	Best fly index: 14 	Fitness value: 710.5072748004904
Iteration: 8 	Best fly index: 22 	Fitness value: 703.834756458099
Iteration: 9 	Best fly index: 3 	Fitness value: 700.1281415948405
Iteration: 10 	Best fly index: 3 	Fitness value: 700.1281415948405
Iteration: 11 	Best fly index: 2 	Fitness value: 699.1050885654532
Iteration: 12 	Best fly index: 23 	Fitness value: 695.2545230046708
Iteration: 13 	Best fly index: 43 	Fitness value: 691.6099188714479
Iteration: 14 	Best fly index: 2 	Fitness value: 688.338740441787
Iteration: 15 	Best fly index: 43 	Fitness value: 688.0054164757564
Iteration: 16 	Best fly index: 36 	Fitness value: 685.3553261217025
Iteration: 17 	Best fly index: 23 	Fitness value: 681.2507846556568
Iteration: 18 	Best fly index: 1 	Fitness value: 679.6494952315843
Iteration: 19 	Best fly index: 24 	Fitness value: 677.9550964323297
Iteration: 20 	Best fly index: 26 	Fitness value: 677.1204539490556
Iteration: 21 	Best fly index: 46 	Fitness value: 673.7017807400971
Iteration: 22 	Best fly index: 46 	Fitness value: 673.7017807400971
Iteration: 23 	Best fly index: 47 	Fitness value: 669.4899974529054
Iteration: 24 	Best fly index: 2 	Fitness value: 668.2718991746351
Iteration: 25 	Best fly index: 46 	Fitness value: 667.2732535376415
Iteration: 26 	Best fly index: 46 	Fitness value: 667.2732535376415
Iteration: 27 	Best fly index: 32 	Fitness value: 665.0526798223401
Iteration: 28 	Best fly index: 3 	Fitness value: 659.8760938752315
Iteration: 29 	Best fly index: 3 	Fitness value: 659.8760938752315
Iteration: 30 	Best fly index: 14 	Fitness value: 655.2563617315201
Iteration: 31 	Best fly index: 46 	Fitness value: 652.997490878018
Iteration: 32 	Best fly index: 14 	Fitness value: 651.9860283997796
Iteration: 33 	Best fly index: 15 	Fitness value: 651.7091519520304
Iteration: 34 	Best fly index: 46 	Fitness value: 650.2154248698257
Iteration: 35 	Best fly index: 15 	Fitness value: 646.9724597925351
Iteration: 36 	Best fly index: 47 	Fitness value: 645.8490302432781
Iteration: 37 	Best fly index: 16 	Fitness value: 643.5586078061666
Iteration: 38 	Best fly index: 47 	Fitness value: 642.5961009601135
Iteration: 39 	Best fly index: 1 	Fitness value: 641.8590355446814
Iteration: 40 	Best fly index: 46 	Fitness value: 641.2172548720043
Iteration: 41 	Best fly index: 46 	Fitness value: 641.2172548720043
Iteration: 42 	Best fly index: 46 	Fitness value: 641.2172548720043
Iteration: 43 	Best fly index: 28 	Fitness value: 638.4345228048252
Iteration: 44 	Best fly index: 39 	Fitness value: 635.2327939442075
Iteration: 45 	Best fly index: 39 	Fitness value: 635.2327939442075
Iteration: 46 	Best fly index: 40 	Fitness value: 634.2390795176361
Iteration: 47 	Best fly index: 14 	Fitness value: 629.8374472582599
Iteration: 48 	Best fly index: 14 	Fitness value: 629.8374472582599
Iteration: 49 	Best fly index: 45 	Fitness value: 628.7506468551181

Final best fitness:	 622.3046990056312

Best fly position:
 [0.48185486 0.20648891 0.15057137 ... 0.46682522 0.00753556 0.24251811]

#### CONVERT FITNESS VALUES INTO ARRAYS

In [31]:
new_arr = []
for i in range(len(fitness)):
    new_arr.append([fitness[i]])

z_fitness = np.array(new_arr)
z_fitness

array([[ 622.30469901],
       [ 627.6817323 ],
       [ 627.50648623],
       [ 640.1251006 ],
       [ 654.61660586],
       [ 642.63741383],
       [ 626.76581897],
       [ 632.30313079],
       [ 641.46366296],
       [ 673.71044125],
       [ 760.11580091],
       [ 747.43904513],
       [ 640.05282931],
       [ 631.80436797],
       [ 634.84904591],
       [ 644.01158647],
       [ 669.14441649],
       [ 722.48827203],
       [ 890.76172536],
       [ 695.28135526],
       [ 632.73347009],
       [ 627.05407542],
       [ 628.1696805 ],
       [ 645.48408073],
       [ 682.59377992],
       [ 636.37269458],
       [ 637.98181058],
       [ 636.11677584],
       [ 640.07659423],
       [ 655.84348594],
       [ 705.73710942],
       [ 894.45110857],
       [1529.20273511],
       [3396.45367608],
       [2039.60528845],
       [ 942.86984094],
       [ 663.89845894],
       [ 637.85044273],
       [ 636.30807297],
       [ 653.76441681],
       [ 629.4729196 ],
       [ 632.23396332],
       [ 645.8405679 ],
       [ 642.22688773],
       [ 641.0632189 ],
       [ 628.75064686],
       [ 632.66241101],
       [ 648.67101113],
       [ 678.5100754 ],
       [ 626.33917446]])

## Feature Selection

#### DEFINE BINARY CONVERSION FUNCTION

In [32]:
def binary_conversion(X, thres, N, dim):
    Xbin = np.zeros([N, dim], dtype='int')
    for i in range(N):
        for d in range(dim):
            if X[i,d] > thres:
                Xbin[i,d] = 1
            else:
                Xbin[i,d] = 0

    return Xbin

#### FEATURE SELECTION USING FITNESS

In [44]:
# Best feature subset
dim = X_train.shape[1]
thres = 0.7
Gbin       = binary_conversion(A, thres, 1, dim)
Gbin       = Gbin.reshape(dim)
pos        = np.asarray(range(0, dim))
sel_index  = pos[Gbin == 1]
num_feat   = len(sel_index)
# Create dictionary
opt_data = {'sf': sel_index, 'nf': num_feat}

In [45]:
print(Gbin)
print(sel_index)
print(num_feat)

[0 0 0 ... 0 0 0]
[   3    7   17   19   31   49   52   60   76   80   82   90   94   98
  104  107  114  115  121  128  133  149  160  163  165  168  170  176
  181  183  190  201  230  236  243  245  246  252  253  279  287  292
  304  309  313  317  320  323  347  356  357  361  367  371  374  382
  385  388  402  405  410  414  418  421  424  430  432  458  460  463
  464  480  483  484  490  495  507  514  515  517  521  528  541  550
  560  565  575  577  594  615  617  624  651  652  661  664  679  691
  698  700  710  713  714  723  728  733  738  757  759  760  781  782
  796  799  800  803  805  808  816  821  827  843  851  853  876  880
  886  900  901  902  922  924  928  933  937  947  953  955  960  965
  967  970  971  975  977  982  984  985  988  999 1006 1010 1012 1020
 1027 1054 1070 1084 1093 1094 1099 1107 1108 1109 1114 1119 1120 1125
 1127 1131 1140 1142 1144 1150 1155 1159 1163 1173 1196 1200 1202 1203
 1213 1225 1226 1231 1236 1254 1256 1261 1281 1284 1290 1313 1319 1324
 1329 1334 1344 1354 1357 1360 1372 1378 1389 1390 1395 1406 1411 1416
 1441 1450 1464 1470 1481 1485 1486 1491 1494 1505 1506 1508 1520 1525
 1530 1532 1538 1547 1549 1552 1557 1560 1561 1567 1572 1576 1583 1601
 1608 1620 1630 1632 1635 1637 1643 1644 1668 1672 1680 1682 1701 1719
 1720 1724 1731 1733 1739 1755 1766 1784 1786 1788 1800 1810 1816 1817
 1830 1845 1848 1850 1859 1866 1874 1884 1886 1888 1889 1903 1910 1917
 1920 1925 1939 1952 1954 1959 1969 1973 1995 1999 2000 2003 2010 2014
 2022 2026 2031 2040 2051 2052 2057 2081 2089 2097 2105 2121 2122 2127
 2139 2143 2151 2152 2160 2161 2162 2165 2173 2179 2181 2189 2195 2202
 2218 2229 2233 2235 2243 2244 2247 2248 2249 2256 2257 2259 2264]
335

In [46]:
opt_data['sf']

array([   3,    7,   17,   19,   31,   49,   52,   60,   76,   80,   82,
         90,   94,   98,  104,  107,  114,  115,  121,  128,  133,  149,
        160,  163,  165,  168,  170,  176,  181,  183,  190,  201,  230,
        236,  243,  245,  246,  252,  253,  279,  287,  292,  304,  309,
        313,  317,  320,  323,  347,  356,  357,  361,  367,  371,  374,
        382,  385,  388,  402,  405,  410,  414,  418,  421,  424,  430,
        432,  458,  460,  463,  464,  480,  483,  484,  490,  495,  507,
        514,  515,  517,  521,  528,  541,  550,  560,  565,  575,  577,
        594,  615,  617,  624,  651,  652,  661,  664,  679,  691,  698,
        700,  710,  713,  714,  723,  728,  733,  738,  757,  759,  760,
        781,  782,  796,  799,  800,  803,  805,  808,  816,  821,  827,
        843,  851,  853,  876,  880,  886,  900,  901,  902,  922,  924,
        928,  933,  937,  947,  953,  955,  960,  965,  967,  970,  971,
        975,  977,  982,  984,  985,  988,  999, 1006, 1010, 1012, 1020,
       1027, 1054, 1070, 1084, 1093, 1094, 1099, 1107, 1108, 1109, 1114,
       1119, 1120, 1125, 1127, 1131, 1140, 1142, 1144, 1150, 1155, 1159,
       1163, 1173, 1196, 1200, 1202, 1203, 1213, 1225, 1226, 1231, 1236,
       1254, 1256, 1261, 1281, 1284, 1290, 1313, 1319, 1324, 1329, 1334,
       1344, 1354, 1357, 1360, 1372, 1378, 1389, 1390, 1395, 1406, 1411,
       1416, 1441, 1450, 1464, 1470, 1481, 1485, 1486, 1491, 1494, 1505,
       1506, 1508, 1520, 1525, 1530, 1532, 1538, 1547, 1549, 1552, 1557,
       1560, 1561, 1567, 1572, 1576, 1583, 1601, 1608, 1620, 1630, 1632,
       1635, 1637, 1643, 1644, 1668, 1672, 1680, 1682, 1701, 1719, 1720,
       1724, 1731, 1733, 1739, 1755, 1766, 1784, 1786, 1788, 1800, 1810,
       1816, 1817, 1830, 1845, 1848, 1850, 1859, 1866, 1874, 1884, 1886,
       1888, 1889, 1903, 1910, 1917, 1920, 1925, 1939, 1952, 1954, 1959,
       1969, 1973, 1995, 1999, 2000, 2003, 2010, 2014, 2022, 2026, 2031,
       2040, 2051, 2052, 2057, 2081, 2089, 2097, 2105, 2121, 2122, 2127,
       2139, 2143, 2151, 2152, 2160, 2161, 2162, 2165, 2173, 2179, 2181,
       2189, 2195, 2202, 2218, 2229, 2233, 2235, 2243, 2244, 2247, 2248,
       2249, 2256, 2257, 2259, 2264])

In [47]:
new_data = df.iloc[:,opt_data['sf']]

In [48]:
new_data

,yVel1,yS1,yA2,yS2,yS3,y5,xA5,x6,xA7,xC7,...,yVel187,nS187,x188,yVel188,xA188,yA188,x189,y189,yVel189,xC189
0,0.299389,0.500713,0.517949,0.469741,0.540453,0.034624,0.505155,0.276857,0.510204,0.463002,...,0.989043,0.000000,0.575839,0.025296,0.497462,0.505051,0.895221,0.296274,0.163462,0.537155
1,0.366191,0.500713,0.517949,0.469741,0.540453,0.483073,0.505155,0.460860,0.510204,0.463002,...,0.367046,0.000000,0.863758,0.713994,0.497462,0.505051,0.018916,0.801788,0.078125,0.537155
2,0.227291,0.500713,0.517949,0.469741,0.540453,0.302261,0.505155,0.699224,0.510204,0.467230,...,0.233460,0.000000,0.529650,0.210934,0.497462,0.505051,0.037654,0.117615,0.220353,0.571125
3,0.821181,0.500713,1.000000,0.469741,0.540453,0.756984,0.371134,0.875882,0.545918,0.463002,...,0.742941,0.000000,0.716610,0.813137,0.436548,0.994949,0.730728,0.963159,0.809295,0.537155
4,0.782892,0.500713,0.517949,0.469741,0.540453,0.425130,0.005155,0.920898,0.000000,0.463002,...,0.242309,0.000000,0.049169,0.944920,0.000000,0.979798,0.072818,0.025276,0.734375,0.537155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23304,0.181670,0.500713,0.005128,0.475504,0.540453,0.703954,0.005155,0.315585,0.510204,0.463002,...,0.018963,0.071429,0.206210,0.936761,0.497462,0.005051,0.417694,0.082861,0.358974,0.537155
23305,0.297760,0.500713,0.153846,0.295389,0.540453,0.896603,0.463918,0.698637,0.433673,0.463002,...,0.108723,0.000000,0.883843,0.203998,0.472081,0.151515,0.537476,0.353621,0.367388,0.520170
23306,0.426477,0.500713,0.517949,0.469741,0.540453,0.138317,0.505155,0.105254,0.510204,0.463002,...,0.974294,0.000000,0.433101,0.158711,0.497462,0.505051,0.844817,0.217288,0.119792,0.537155
23307,0.356008,0.500713,0.517949,0.119597,0.540453,0.733606,0.005155,0.504466,0.000000,0.463002,...,0.164349,0.000000,0.081769,0.068543,0.000000,0.005051,0.620671,0.740924,0.373397,0.537155
23308,0.577189,0.500713,0.533333,0.400576,0.721683,0.580137,0.489691,0.426716,0.545918,0.437632,...,0.323641,0.000000,0.247393,0.269278,0.497462,0.505051,0.005693,0.519106,0.193109,0.598726

## Classification after Optimization

In [49]:
#feature variables
X = new_data.values

#target variable
y = df['Swarm_Behaviour'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=23)

print("Shape of X_train:", X.shape)
print("Shape of y_train:", y.shape)

Shape of X_train: (23309, 335)
Shape of y_train: (23309,)

In [50]:
models1 = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models1['Logistic Regression'] = LogisticRegression(solver='lbfgs', max_iter=2000)

# Support Vector Machines
from sklearn.svm import SVC
models1['Support Vector Machines'] = SVC(kernel='linear')

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models1['Decision Trees'] = DecisionTreeClassifier()

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models1['Random Forest'] = RandomForestClassifier()


# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models1['K-Nearest Neighbor'] = KNeighborsClassifier()

# Neural Networks
from sklearn.neural_network import MLPClassifier
models1['Neural Networks'] = MLPClassifier()

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix

accuracy1 = {}

for key in models1.keys():

    # Fit the classifier
    models1[key].fit(X_train, y_train)

    #     # Make predictions
    predictions1 = models1[key].predict(X_test)

    #     # Calculate metrics
    accuracy1[key] = accuracy_score(predictions1, y_test)

In [52]:
df_model1 = pd.DataFrame(index=models1.keys(), columns=['Accuracy'])
df_model1['Accuracy'] = accuracy1.values()

df_model1

                         Accuracy
Logistic Regression      0.899900
Support Vector Machines  0.896754
Decision Trees           0.871872
Random Forest            0.871014
K-Nearest Neighbor       0.888746
Neural Networks          0.897755

In [53]:
from IPython.display import display_html
from itertools import chain,cycle
def display_side_by_side(*args,titles=cycle([''])):
    html_str=''
    for df,title in zip(args, chain(titles,cycle(['</br>'])) ):
        html_str+='<th style="text-align:center"><td style="vertical-align:top">'
        html_str+=f'<h3 style="text-align: center;">{title}</h2>'
        html_str+=df.to_html().replace('table','table style="display:inline"')
        html_str+='</td></th>'
    display_html(html_str,raw=True)

In [54]:
display_side_by_side(df_model,df_model1, titles=['Classification without DFO','Classification with DFO'])

,Accuracy
Logistic Regression,0.881596
Support Vector Machines,0.877020
Decision Trees,0.872301
Random Forest,0.871586
K-Nearest Neighbor,0.888460
Neural Networks,0.896897
,Accuracy
Logistic Regression,0.899900
Support Vector Machines,0.896754
Decision Trees,0.871872
Random Forest,0.871014
K-Nearest Neighbor,0.888746
Neural Networks,0.897755